### PR TITLE
pull request for test_server.py

### PR DESCRIPTION
**Pull request by Bq18**

### CODE REVIEW

**Comment by YuqianZhang** [comment]
Hi Biqi,
Your  test_python.py does not pass the test when I test it on my side. Are you sure that you upload the correct version?  
Like for line 53, it supposed to be /customers rather than /customer.
Please let me know once you have your code polished.

**Comment by Bq18** [comment]
Hi Yuqian,

Thanks for your reminding! I failed to upload the updated version.  I just make the change and it should work now. Please let me know if there is any problem. Thanks!

Biqi

**Review by YuqianZhang — COMMENTED** [review]
Your code has been reviewed. One thing need to improve is the code coverage(our goal is up to 90%)
Your current code coverage is 88%. 
Reconsider your code from line 160, you might get a hint of how to improve the code coverage.

**Comment by Bq18** [comment]
Hi Yuqian,

That's a problem. I have tried to write several test cases but they didn't improve the coverage. I may need your help. 

For example, I uncommented the code of the test case "test_mock_search_data" from Line 168 to 173 in my code which I think it may cover the missing line 108 in server.py. Also, I wrote the test case to test the create_customer_with_no_content_type. But the coverage for the new version is still 88%.

Besides that, I wrote the test case for the internal error to cover the missing lines 82-85 following the class note " Test Drive Development" on Page 35. But the test failed to pass. 

And I have no idea on test case for the missing line 73-75 of "415_UNSUPPORTED_MEDIA_TYPE". 

Any advice? Thanks!

Biqi

**Pull request merged**
